title: The Strawbridge Lab
description: Quantifying human development
baseurl: ""
#url: https://strawbridgelab.com
url: stanleystrawbridge.github.io

theme: minima    
plugins: [jekyll-feed]
markdown: kramdown

header_pages:
  - index.md
  #- research.md
  - people.md
  - publications.md
  - public engagement.md
  - news.md
  - join.md
