# _config.yml
title: The Strawbridge Lab
description: Quantifying human development.
baseurl: ""                             
url: "https://stanleystrawbridge.github.io"

theme: minima                         
plugins: [ jekyll-feed ]               
markdown: kramdown                     

header_pages:
  - index.md
  - people.md
  - publications.md
  - public engagement.md
  - news.md
  - join.md
