# _config.yml
title: The Strawbridge Lab
description: Quantitative biology of human development, from chip to dish
baseurl: ""                             
url: "https://stanleystrawbridge.github.io"

theme: minima                         
plugins: [ jekyll-feed ]               
markdown: kramdown                     

header_pages:
  - index.md
  - people.md
  - publications.md
  - public engagement.md
  - news.md
  - joining the lab.md
