title: The Strawbridge Lab
description: Quantifying human development
url: https://www.strawbridgelab.com
baseurl: ""

theme: minima    
plugins: [jekyll-feed]
markdown: kramdown

header_pages:
  - index.md
  #- research.md
  - people.md
  - publications.md
  - public engagement.md
  - news.md
  - join.md
